// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCfnPqxfIH6MCoduKCnZLjQPwrAu-250w',
    appId: '1:379031422043:web:33cd667b84991c6194ab7e',
    messagingSenderId: '379031422043',
    projectId: 'fir-series-91991',
    authDomain: 'fir-series-91991.firebaseapp.com',
    storageBucket: 'fir-series-91991.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA42X-hFtHuLvCUkdWI7g26FdTwZm5F3Jg',
    appId: '1:379031422043:android:7f93b4c0e20b35ae94ab7e',
    messagingSenderId: '379031422043',
    projectId: 'fir-series-91991',
    storageBucket: 'fir-series-91991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdrsZMkqHBCOPcZEdDiTOXkudEA-zaAEU',
    appId: '1:379031422043:ios:2653c203cfb31bbb94ab7e',
    messagingSenderId: '379031422043',
    projectId: 'fir-series-91991',
    storageBucket: 'fir-series-91991.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );
}
